# Generated by Django 4.2.5 on 2023-11-09 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_customer_state_alter_orderplaced_status_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wishlist',
            old_name='Product',
            new_name='product',
        ),
    ]
